name: Run Tests and Notify in Slack

on:
  push:
    branches:[main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run Tests
      run: python -m unittest discover tests
      
    - uses: actions/checkout@master
    - name: Slack Notification Demo
      uses: bryannice/gitactions-slack-notification@2.0.0
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: 'Demo''ing the Slack Notification'
          SLACK_TITLE: 'Slack Notification Demo'



