name:  Telegram Notificatioa Demo

on:
  push:
    branches:
      - main
      - master

- name: send telegram message on push        
  uses: appleboy/telegram-action@0.0.3
  with:
    to: ${{ secrets.TELEGRAM_TO }}
    token: ${{ secrets.TELEGRAM_TOKEN }}
    message: send photo message
  env:
    TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
