name:  Telegram Notificatioa Demo

on:
  push:
    branches: [main]
- name: send telegram message on push        
  uses: appleboy/telegram-action@0.0.3
  with:
    to: ${{ secrets.TELEGRAM_TO }}
    token: ${{ secrets.TELEGRAM_TOKEN }}
    message: test message
  env:
    TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
