- name: Run Tests
  id: tests
  run: |
    test_result=$(python -m unittest discover 2>&1)
    if [[ "$test_result" == *"Ran 0 tests in"* ]]; then
      echo "Tests Failed"
    else
      echo "Tests Passed"
    fi
  continue-on-error: true

- name: Send Telegram message on push
  if: steps.tests.outcome != 'success'
  uses: appleboy/telegram-action@0.0.3
  with:
    to: ${{ secrets.TELEGRAM_TO }}
    token: ${{ secrets.TELEGRAM_TOKEN }}
    message: |
      **GitHub Action Notification**

      Repository: MyRepo pythone-gitaction
      Branch: ${{ github.ref }}
      Commit: ${{ github.sha }}
      Author: ${{ github.actor }}
      Message: ${{ github.event.head_commit.message }}
      Status: Tests Failed
  env:
    TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

- name: Send Telegram message on push (Success)
  if: steps.tests.outcome == 'success'
  uses: appleboy/telegram-action@0.0.3
  with:
    to: ${{ secrets.TELEGRAM_TO }}
    token: ${{ secrets.TELEGRAM_TOKEN }}
    message: |
      **GitHub Action Notification**

      Repository: MyRepo pythone-gitaction
      Branch: ${{ github.ref }}
      Commit: ${{ github.sha }}
      Author: ${{ github.actor }}
      Message: ${{ github.event.head_commit.message }}
      Status: Tests Passed
  env:
    TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

